// Regenerates docs/economy-report.md: `npm run economy` (about a minute). Deterministic: same seeds every run.
// It uses the same bots and settlement code as the game, so the tables cannot drift from the rules.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { it } from "vitest";
import { FIELD_GOLD_PER_RF, FLASK_PRICE, KEY_PRICE, POOL_SHARE } from "../src/game/config";
import { NO_PERKS, mergePerks } from "../src/game/catalog";
import { settleRound } from "../src/game/economy";
import { simulateFogMany, simulateRound, type Cohort } from "../src/game/sim";

const blessed = mergePerks({ goldPct: 20, radius: 1 });
// Legendary Pathfinder (-35% light per step, +1 radius) + Hoverer family perk (-25%, total capped at 45%) + Friend's Blessing.
const strong = mergePerks({ stepDiscount: 0.35, radius: 1 }, { stepDiscount: 0.25 }, { goldPct: 20, radius: 1 });

const strategies = [
  { name: "Unperked, 1 flask", perks: NO_PERKS, flasks: 1 },
  { name: "Unperked, 2 flasks", perks: NO_PERKS, flasks: 2 },
  { name: "Unperked, 3 flasks", perks: NO_PERKS, flasks: 3 },
  { name: "Friend's Blessing, 2 flasks", perks: blessed, flasks: 2 },
  { name: "Strongest build, 3 flasks", perks: strong, flasks: 3 },
];

const pct = (n: number) => `${Math.round(n * 100)}%`;

it("writes the economy report", { timeout: 600_000 }, () => {
  const RUNS = 80;
  const stats = strategies.map(s => ({ ...s, ...simulateFogMany(RUNS, s.flasks, s.perks), cost: s.flasks * FLASK_PRICE + KEY_PRICE }));
  const out: string[] = [];

  out.push("# Emberdeep economy report", "");
  out.push(
    "Generated by `npm run economy` from the same code the game runs. Every number is a simulation with bots, not a measurement of players.",
    "The bots see only what the lantern lights (\"fog\" bots) and rarely die, so treat the returns as an upper bound for real players.",
    `Descent cost = one entry key (${KEY_PRICE} RF) + lantern flasks (${FLASK_PRICE} RF each). One-off purchases (Delver mints, weapons, armor, passes) are extra spend that also goes through the 25/8/67 split; they are not in the return columns.`,
    `The pool is always ${pct(POOL_SHARE)} of everything spent. A delver gets \`pool × their gold / all gold\`, so the total paid out is fixed: nothing here can print or drain tokens.`,
    "",
  );

  out.push(`## A. What a descent yields (${RUNS} seeded descents per strategy)`, "");
  out.push("| Strategy | Cost per descent | Gold banked per RF spent | Died | Avg deepest floor |", "| --- | --- | --- | --- | --- |");
  for (const s of stats) out.push(`| ${s.name} | ${s.cost} RF | ${s.goldPerRf.toFixed(2)} | ${pct(s.deathRate)} | ${s.avgDepth.toFixed(1)} |`);

  const crowdRates = [0.7, 1.0, FIELD_GOLD_PER_RF, 2.0, 2.8];
  const crowdSpend = 20_000;
  out.push("", `## B. Sensitivity to the crowd's skill (the demo assumes ${FIELD_GOLD_PER_RF} gold per RF)`, "");
  out.push(`One delver making 10 descents against a crowd that spent ${crowdSpend.toLocaleString("en-US")} RF and banked the given gold per RF. Cells are RF received / RF spent on the descents.`, "");
  out.push(`| Strategy | ${crowdRates.map(r => `crowd ${r}`).join(" | ")} |`, `| --- | ${crowdRates.map(() => "---").join(" | ")} |`);
  for (const s of stats) {
    const spend = s.cost * 10, gold = s.goldPerRf * spend;
    const cells = crowdRates.map(r => pct(settleRound((crowdSpend + spend) * POOL_SHARE, gold, crowdSpend * r).payout / spend));
    out.push(`| ${s.name} | ${cells.join(" | ")} |`);
  }
  out.push("", "A cell scales with `your gold per RF / the crowd's gold per RF`. If the demo's 1.4 is wrong by a factor of two, every return above moves by about the same factor, but the sum paid out to the whole crowd stays 67% of spend.");

  const sizes = [2_000, 20_000, 200_000];
  out.push("", `## C. Sensitivity to crowd size (crowd of unperked 2-flask delvers at ${FIELD_GOLD_PER_RF} gold per RF)`, "");
  out.push(`| Strategy | ${sizes.map(n => `crowd ${n.toLocaleString("en-US")} RF`).join(" | ")} |`, `| --- | ${sizes.map(() => "---").join(" | ")} |`);
  for (const s of stats) {
    const spend = s.cost * 10, gold = s.goldPerRf * spend;
    const cells = sizes.map(n => pct(settleRound((n + spend) * POOL_SHARE, gold, n * FIELD_GOLD_PER_RF).payout / spend));
    out.push(`| ${s.name} | ${cells.join(" | ")} |`);
  }
  out.push("", "In a tiny crowd one delver is a large part of the gold, so its own spend dilutes its share. Returns settle as the crowd grows.");

  out.push("", "## D. Whole rounds: what happens when more players run the strongest build", "");
  out.push("Each row is a whole round with players in the given proportions (share of all descents). \"Paid out / spent\" is everything paid to everyone divided by everything spent.", "");
  out.push("| Mix (unperked / Friend's Blessing / strongest) | Paid out / spent | Unperked | Blessing | Strongest |", "| --- | --- | --- | --- | --- |");
  for (const [a, b, c] of [[100, 0, 0], [90, 8, 2], [70, 20, 10], [50, 30, 20], [20, 30, 50], [0, 0, 100]]) {
    const cohorts: Cohort[] = [
      { name: "base", perks: NO_PERKS, flasks: 2, share: a },
      { name: "blessed", perks: blessed, flasks: 2, share: b },
      { name: "strong", perks: strong, flasks: 3, share: c },
    ].filter(x => x.share > 0);
    const sim = simulateRound(cohorts, 3_000, 40);
    const f = (n: string) => (sim.rtp[n] === undefined ? "n/a" : pct(sim.rtp[n]));
    out.push(`| ${a} / ${b} / ${c} | ${(sim.overall * 100).toFixed(1)}% | ${f("base")} | ${f("blessed")} | ${f("strong")} |`);
  }
  out.push(
    "",
    "The strongest build earns well above average only while few others play it. Its edge is paid by everyone else's gold, and it shrinks as it spreads (compare the rows); if everyone has it, the round pays every delver exactly 67% again.",
    "That is why an edge is worth buying but cannot be farmed without limit: the more delvers buy it, the less each one's gold share is worth.",
    "",
  );

  writeFileSync(fileURLToPath(new URL("../docs/economy-report.md", import.meta.url)), out.join("\n"));
});
