// Regenerates docs/light-tuning.md: `npm run tuning` (a few minutes). Deterministic: the same seeds every run.
// It plays the real game rules with bots, so the tables cannot drift from the code. The bots are not people: they show
// how far a given amount of oil carries a descent, not how a player will feel.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { it } from "vitest";
import { BOSS_DEPTH, FLASK_LIGHT } from "../src/game/config";
import { simulateDiveRun, simulateFogRun, type BotStyle } from "../src/game/sim";
import { DEFAULT_TUNING, countLight, lightTally, resetLightTally, withTuning, type Tuning } from "../src/game/tuning";

const RUNS = 40;
const seeds = Array.from({ length: RUNS }, (_, i) => 1_000 + i * 7_919);
const avg = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / Math.max(1, xs.length);
const pct = (x: number) => `${Math.round(x * 100)}%`;

type Scenario = { name: string; note: string; patch: Partial<Tuning> };
const scenarios: Scenario[] = [
  {
    name: "Before",
    note: "Creatures drop nothing. Props hold 4-14 light, with a 15% to 75% chance.",
    patch: { propOilScale: 2 / 3, propOilChance: [0.15, 0.75], killDropChance: [0, 0], killDropLight: [0, 0] },
  },
  {
    name: "Creatures only",
    note: "Creatures drop 5-10 light (35% to 80%), props as before.",
    patch: { propOilScale: 2 / 3, propOilChance: [0.15, 0.75] },
  },
  {
    name: "Props only",
    note: "Props hold 6-21 light with a 30% to 90% chance, creatures drop nothing.",
    patch: { killDropChance: [0, 0], killDropLight: [0, 0] },
  },
  {
    name: "Chosen",
    note: "Both: what the game uses.",
    patch: {},
  },
  {
    name: "Too generous",
    note: "The chosen values, plus creatures dropping 8-14 light (50% to 90%) and half as many oil jars again.",
    patch: { killDropChance: [0.5, 0.9], killDropLight: [8, 14], oilJarCount: 1.5 },
  },
];

function dive(flasks: number, style: BotStyle = {}) {
  const rs = seeds.map(seed => simulateDiveRun(seed, flasks, undefined, undefined, style));
  const at = (d: number) => rs.filter(r => r.depth >= d).length / RUNS;
  return { depth: avg(rs.map(r => r.depth)), p3: at(3), p5: at(5), p7: at(BOSS_DEPTH) };
}

it("writes docs/light-tuning.md", { timeout: 1_800_000 }, () => {
  const out: string[] = [
    "# How much oil the deep gives back",
    "",
    "Generated by `npm run tuning` from the same code the game runs. Every number is a simulation with bots, not a measurement of players.",
    "",
    "## The question",
    "",
    `A flask holds ${FLASK_LIGHT} light and a descent may start with up to five. Exploring one of the big first floors takes about 130 steps, and a creature's blow drinks a few light more, so a floor costs roughly 130-170 light and the floors get dearer with depth. If the deep gave nothing back, two flasks would end on floor 2 or 3 and the boss on floor ${BOSS_DEPTH} could not be reached at all. If it gave too much, flasks would stop mattering and a descent would never end.`,
    "",
    "Light comes back from four places: oil jars lying on the floor, broken props, defeated creatures (new) and level-ups (+10 each). Props and creatures give oil more often the lower the lantern is, so a delver running dry is helped and one with a full lantern is not.",
    "",
    "## How it was measured",
    "",
    `- **Diver:** a bot that only wants to go down. It fights what is in its way, picks up loot within four steps of its path, takes every stairs at once and never goes home, so it stops only when the light is gone. Where it stops is how far that oil carries a player who does not collect. The *newcomer* finds the stairs by exploring; the *expert* already knows where they are. Both dodge marked tiles; the *sloppy* one does not.`,
    `- **Collector:** the bot behind the economy report. It gathers loot and leaves when the walk home would use up its reserve. Its gold per RF shows how much the extra oil inflates the economy (the simulated crowd is recalibrated to it).`,
    `- ${RUNS} descents per cell, the same seeds for every scenario.`,
    "",
    "## Results",
    "",
  ];

  const results = scenarios.map(sc => withTuning(sc.patch, () => {
    const n1 = dive(1), n2 = dive(2), n3 = dive(3), n5 = dive(5);
    const e3 = dive(3, { knowsMap: true }), e5 = dive(5, { knowsMap: true });
    const s3 = dive(3, { dodge: false });
    const collector = seeds.map(seed => simulateFogRun(seed, 2));
    const gold = collector.reduce((n, r) => n + r.banked, 0) / collector.reduce((n, r) => n + r.spent, 0);
    resetLightTally();
    countLight(() => seeds.forEach(seed => simulateDiveRun(seed, 3)));
    const tally = Object.fromEntries(Object.entries(lightTally).map(([k, v]) => [k, v / RUNS])) as typeof lightTally;
    return { sc, n1, n2, n3, n5, e3, e5, s3, gold, tally };
  }));

  out.push(
    "### Mean floor reached, and the share of descents that reach floors 3, 5 and the boss floor",
    "",
    `| Scenario | 1 flask | 2 flasks | 3 flasks | 5 flasks | Expert, 3 flasks | Expert, 5 flasks | Sloppy, 3 flasks |`,
    `| --- | --- | --- | --- | --- | --- | --- | --- |`,
  );
  for (const r of results) {
    const cell = (x: ReturnType<typeof dive>) => `${x.depth.toFixed(1)} (${pct(x.p3)} / ${pct(x.p5)} / ${pct(x.p7)})`;
    out.push(`| **${r.sc.name}** | ${cell(r.n1)} | ${cell(r.n2)} | ${cell(r.n3)} | ${cell(r.n5)} | ${cell(r.e3)} | ${cell(r.e5)} | ${cell(r.s3)} |`);
  }
  out.push(
    "",
    "Each cell is the mean deepest floor, then the share of descents that got to floor 3 / floor 5 / floor " + BOSS_DEPTH + ". These are newcomers unless the column says expert.",
    "",
    "### Where the light came from and went, per descent (newcomer diver, 3 flasks)",
    "",
    "| Scenario | Start | Oil jars | Props | Creatures | Levels | Steps | Blows taken | Collector gold per RF (2 flasks) |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const r of results) {
    const t = r.tally;
    out.push(`| **${r.sc.name}** | ${3 * FLASK_LIGHT} | ${Math.round(t.jars)} | ${Math.round(t.props)} | ${Math.round(t.kills)} | ${Math.round(t.levels)} | -${Math.round(t.steps)} | -${Math.round(t.hits)} | ${r.gold.toFixed(2)} |`);
  }
  out.push("", "### What each scenario means", "");
  for (const r of results) out.push(`- **${r.sc.name}.** ${r.sc.note}`);

  const chosen = results.find(r => r.sc.name === "Chosen")!;
  const before = results.find(r => r.sc.name === "Before")!;
  out.push(
    "",
    "## What was chosen, and why",
    "",
    `- **Creatures drop ${DEFAULT_TUNING.killDropLight[0]}-${DEFAULT_TUNING.killDropLight[1]} light** with a ${pct(DEFAULT_TUNING.killDropChance[0])} chance when the lantern is full, rising to ${pct(DEFAULT_TUNING.killDropChance[1])} when it is nearly empty. This was the most efficient lever in the wider sweep of 120 combinations: it added the most floors for the least extra gold, and it rewards fighting, which costs light.`,
    `- **Props hold more oil and give it more often:** urns 6-10, crates 9-15, barrels 12-21, with a ${pct(DEFAULT_TUNING.propOilChance[0])} to ${pct(DEFAULT_TUNING.propOilChance[1])} chance.`,
    `- **Oil jars stay at ${DEFAULT_TUNING.oilJarLight} light and the usual number.** Adding jars was the strongest lever but inflated the gold the most (see "Too generous").`,
    `- **Levels stay at +${DEFAULT_TUNING.levelLight} light each**, as designed.`,
    "",
    `With the chosen values a 2-flask descent reaches floor ${chosen.n2.depth.toFixed(1)} on average (${pct(chosen.n2.p3)} reach floor 3; it was ${before.n2.depth.toFixed(1)} and ${pct(before.n2.p3)}), 3 flasks reach floor ${chosen.n3.depth.toFixed(1)}, and the most a player can carry, 5 flasks, reach floor ${chosen.n5.depth.toFixed(1)}, with ${pct(chosen.n5.p7)} of newcomers and ${pct(chosen.e5.p7)} of experts getting as far as Cerberus (before: ${pct(before.n5.p7)} and ${pct(before.e5.p7)}). The boss is reachable but not handed over, and every extra flask still carries a descent further, though less than it used to (one flask takes a newcomer to floor ${chosen.n1.depth.toFixed(1)}, five to floor ${chosen.n5.depth.toFixed(1)}; before: ${before.n1.depth.toFixed(1)} and ${before.n5.depth.toFixed(1)}), because oil now comes back to whoever is running dry.`,
    "",
    `The price is gold: a collector banks ${chosen.gold.toFixed(2)} gold per RF instead of ${before.gold.toFixed(2)}, because it stays deeper where loot is worth more. The simulated crowd is set from the bots, so this moves the crowd's rate and not anyone's share.`,
    "",
    "## What this does not show",
    "",
    "Bots are not people. A player who explores less, fights less, or remembers the floors will go further on the same oil; one who fights everything will go less far. The bots never buy potions (an Oil Vial is +30 light, a Healing Draught +60), which players will. The numbers show that the amount of oil is in a range where a descent can be carried on; they do not promise how it feels.",
    "",
  );

  writeFileSync(fileURLToPath(new URL("../docs/light-tuning.md", import.meta.url)), out.join("\n"));
});
